### ISSUE TITLE
six usage

### ISSUE THREAD

**Issue by pgajdos** [matwey/django-eremaea2#14]
I am not sure if you need to support Python 2. If not, then I think at least dependency of `six` could be removed.

**Comment by matwey** [comment]
Frankly speaking, I don't see any harm from supporting Python 2.x currently. I know that it has been deprecated long time ago but still.

**Comment by pgajdos** [comment]
I guess there is no harm until you want to really support python 2. I couldn't find any reference, hence I am asking here as some projects dropped python 2 support but still use six unnecessarily.

**Comment by matwey** [comment]
I personally don't use this package with python 2, and I don't know anybody does. So, I agree that we can drop python 2 support in the next release.

**Comment by matwey** [comment]
I saw your six-removing patch in the OBS, could you please make a PR?
